baseURL = "/"
title = "作ったものとか"

hascjklanguage = true

theme = "cheep"
#theme = "beg"
googleAnalytics = "UA-105605213-1"

copyright = "Copyright 2017-2019 Shuhei Kubota"

#pygmentsUseClasses = true
#pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsstyle = "pastie"
pygmentsOptions = "linenos=true"
#pygmentsOptions = "linenos=true, noclasses=true, style=pastie"

enableGitInfo = true

[taxonomies]
  #tag = "tags"
  #category = "categories"

[params]
  Summary = true
  Content = true
  # if both are set to true, summary is shown.
  
  #profileImage = "profile.png"
  #profileTwitter = "chimatter"
  profileHTML = "<object type='image/svg+xml' data='https://img.shields.io/badge/@chimatter-Follow-blue?style=for-the-badge&logo=twitter&logoColor=white&link=https://twitter.com/intent/user?screen_name=chimatter&link=https://twitter.com/intent/follow?screen_name=chimatter' style='margin-top:2em; margin-left:1em'></object>"
  #profileDescription = ""
  