baseURL = "/"
languageCode = "ja-jp"
title = "作ったものとか"

hascjklanguage = true

theme = "beg"
googleAnalytics = "UA-105605213-1"

[taxonomies]
  #tag = "tags"
  #category = "categories"

[params]
  Summary = true  # takes true or false
  Content = true  # takes true or false
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright Me 2016. Powered by Hugo."
