version: 2
jobs:
  build:
    working_directory: ~/ShuheiKubota.github.io.src
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:af:44:7e:43:9c:19:4e:93:1a:0f:b1:fc:ff:93:77"
      - run:
          name: no yes typing on ssh
          command: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - checkout
      - run:
          name: fetch submodules
          command: git submodule update --init --recursive --remote
      - run:
          name: pull publish repos
          command: |
            git clone git@github.com:ShuheiKubota/ShuheiKubota.github.io.git public
      - run:
          name: generate syntax.css via hugo
          command: |
            mkdir static/css
            hugo gen chromastyles --style=pastie > static/css/syntax.css
      - run:
          name: run hugo
          command: hugo --minify
      - run:
          name: publish
          command: |
            cd public
            git config user.email "aaa@example.com"
            git config user.name "CircleCI Job"
            git add . --all --force
            git commit -m "deploy from CircleCI"
            echo yes | git push --force origin master
