version: 2
jobs:
  build:
    working_directory: ~/ShuheiKubota.github.io.src
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: fetch submodules
          command: git submodule update --init --recursive --remote
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo 
      - run:
          name: generate syntax.css via hugo
          command: |
            mkdir static/css
            hugo gen chromastyles --style=pastie > static/css/syntax.css
      - run:
          name: build hugo
          command: hugo
      - save_cache:
          key: public
          paths:
            - ~/ShuheiKubota.github.io.src/public

  deploy:
    working_directory: ~/ShuheiKubota.github.io.src/public
    docker:
      - image: circleci/golang:latest
    steps:
      - restore_cache:
          keys:
            - public
      - add_ssh_keys:
          fingerprints:
            - "5f:3c:94:0b:54:70:0a:f2:32:80:dc:83:04:58:c6:aa"
      - run:
          name: deploy 
          command: |
            git init
            git config user.email "aaa@example.com"
            git config user.name "CircleCI Job"
            git add .
            git commit -m "deploy from CircleCI"
            echo yes | git push -f git@github.com:ShuheiKubota/ShuheiKubota.github.io.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build